experiment:
  name: debug
  save_checkpoint_every: 5000
  validate_every: 5000
  min_validate: 20000
  n_epochs: 20000000
  checkpoint_path: 'experiments/postcvpr_ext_force_new_20240223_152934/checkpoints/step_0000150000.pth'

runner:
  postcvpr_space_ext:
    force_names:
      - 'ext_force_energy'
      - 'gravitational_energy'
    warmup_steps: 100
    optimizer:
      lr: 5e-5
      decay_steps: 50_000
      decay_rate: 5e-1
    material:
      lame_mu_min: 15909
      lame_mu_max: 63636
      lame_lambda_min: 3535.414406069427
      lame_lambda_max: 93333.73508005822
      bending_coeff_min: 6.370782056371576e-08
      bending_coeff_max: 0.0013139737991266374
      density_min: 4.34e-2
      density_max: 7e-1
      wind_min: 0
      wind_max: 10

      energy_type_prob: 'stvk'
    self_col: True

dataloader:
  num_workers: 8
  batch_size: 1
  pyg_data: True
  dataset:
    postcvpr:
      data_root: 'vto_dataset/smpl_parameters'
      smpl_model: 'smpl/SMPL_FEMALE.pkl'
      garment_dict_file: 'garments_dict.pkl'
      split_path: 'datasplits/train.csv'
      val_split_path: 'datasplits/val_sim.csv'
      val_sim_dir: 'simulation_hood_full'
      lookup_steps: 5
      pinned_verts: True
      random_betas: True
      betas_scale: 3.
      n_coarse_levels: 3

criterions:
  postcvpr.ext_force_energy:
  postcvpr.mataug.self_intersection_energy:
    weight: 30000
    norm: 'l1'
  postcvpr.mataug.stretching_energy:
  postcvpr.inertia:
  postcvpr.gravitational_energy:
    z_axis: 1
  postcvpr.collision_penalty:
    weight_start: 5e+3
    weight_max: 5e+5
    eps: 2e-3
    start_rampup_iteration: 50000
    n_rampup_iterations: 100000
  postcvpr.mataug.bending_energy:
  postcvpr.friction_energy:
    mu: 0.5
    friction_radius: 3e-3

model:
  postcvpr_space_ext:
    core_model: 'postcvpr_space'
    architecture: "f,c0,s|f,c0,s|f,c0,s|d:c0,c1|c0,c1|c0,c1|d:c1|c1|c1|u:c0,c1|c0,c1|c0,c1|u:f,c0,s|f,c0,s|f,c0,s"
    collision_radius: 3e-2
    k_world_edges: 1
    n_coarse_levels: 3

device: 'cuda:0'